const UPDATE_COMPANYDETAILS = "UPDATE_COMPANYDETAILS"
const UPDATE_BASICINFO = "UPDATE_BASICINFO"
const UPDATE_PRODUCTDETAILS = "UPDATE_PRODUCTDETAILS"
const UPDATE_LICENSEDETAILS = "UPDATE_LICENSEDETAILS"
const UPDATE_ADDITIONALINFO = "UPDATE_ADDITIONALINFO"
const RESET_IMPORTER_DETAILS = "RESET_IMPORTER_DETAILS"

const UPDATE_EXPORTER_BASIC_INFO = "UPDATE_EXPORTER_BASIC_INFO"
const UPDATE_EXPORTER_COMPANY_DETAILS = "UPDATE_EXPORTER_COMPANY_DETAILS"
const UPDATE_EXPORTER_ADDITIONAL_INFO = "UPDATE_EXPORTER_ADDITIONAL_INFO"
const UPDATE_EXPORTER_LICENSE_DETAILS = "UPDATE_EXPORTER_LICENSE_DETAILS"
const UPDATE_EXPORTER_PRODUCT_DETAILS = "UPDATE_EXPORTER_PRODUCT_DETAILS"
const RESET_EXPORTER_DETAILS = "RESET_EXPORTER_DETAILS"


export { UPDATE_COMPANYDETAILS, UPDATE_BASICINFO, UPDATE_PRODUCTDETAILS, UPDATE_LICENSEDETAILS, UPDATE_ADDITIONALINFO, UPDATE_EXPORTER_BASIC_INFO,  UPDATE_EXPORTER_COMPANY_DETAILS, UPDATE_EXPORTER_ADDITIONAL_INFO, UPDATE_EXPORTER_LICENSE_DETAILS, UPDATE_EXPORTER_PRODUCT_DETAILS, RESET_IMPORTER_DETAILS, RESET_EXPORTER_DETAILS }
